#
# Copyright (c) 2023-present VPMedia
# author: Andras Csizmadia <andras@vpmedia.hu>
# see https://docs.docker.com/compose/compose-file
#
services:
  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - '6379:6379'
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - redis
networks:
  default:
    name: vpmedia_shared_network
