# Copyright (c) 2023-present VPMedia
# author: Andras Csizmadia <andras@vpmedia.hu>

name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Init
        run: ./cli.sh --ci
      - name: Lint
        run: ./cli.sh --lint
      - name: Test
        run: ./cli.sh --test
      - name: Build
        run: ./cli.sh --build
